### ISSUE TITLE
appveyor config on nodejs version

### ISSUE THREAD

**Issue by hirokihokari** [chidimo/Express-API-Template#14]
Did you set anything on appveyor UI, not .appveyor.yml?

I'm asking because my appveyor build with the latest .appveyor config(after 46faf622e20559e40b3a4ee791cd2df81cefe3e3) will fail. Looks like node version is straight up ignored, resulting in the default(?) version of 8 being used, which does not meet a requirement of some dependency package, and the build fails.

I've looked into the appveyor doc, and came to the conclusion that happens to be closer to your code before 46faf622e20559e40b3a4ee791cd2df81cefe3e3. The only major difference is that my config does not specify node version as `matrix` key, but directly under `environment` key.

```
environment:
  nodejs_version: "12"

install:
  - ps: Install-Product node $env:nodejs_version
  - yarn

test_script:
  - node --version
  - yarn --version
  - yarn test

build: off
```

I've dared and suspected your config syntax was incorrect, but the appveyor log of the 46faf622e20559e40b3a4ee791cd2df81cefe3e3 build shows that it correctly detects node version and replaces the default version 8 with the specified version 12, and the build succeeds.

Do you have any configuration done on UI for appveyor?

**Comment by chidimo** [comment]
@hirokihokari  No. I didn't do any extra configuration on the UI.

I'm guessing you're experiencing the same issue a previous reader experienced. His name is Phil and he wrote his workaround in the comments section but I'll repost it here.

## Phil's comments

A workaround I did was to ignore node engine requirements when installing dependencies. In appveyor.yml under install replace `yarn` with `yarn --ignore-engines`.

Then I figured it out after some googling as well as reading the AppVeyor documentation on Node.js (https://www.appveyor.com/docs/lang/nodejs-iojs/). The AppVeyor build image seems to have a default Node.js v8.17.0. In order to use other versions, I added this line in the `install` section before the call to `yarn`:

```
- ps: Install-Product node $env:nodejs_version
```

This installs the desired Node.js version into the build environment.

This is how my `appveyor.yml` looks now (btw I also added commands to display `node` and `npm` versions under `test_script` ):

```
environment:
  matrix:
  - nodejs_version: "12"
install:
  - ps: Install-Product node $env:nodejs_version
  - yarn
test_script:
  - node --version
  - npm --version
  - yarn test
build: off
```

Hope this helps others who encountered a similar problem!
